server:
  port: 9035
  servlet:
    context-path: /forum-analysis
    


spring.jpa.hibernate.ddl-auto: update
spring.datasource.url:  jdbc:mysql://localhost:3309/rapid_dev_external_integration?useUnicode=yes&characterEncoding=UTF-8
spring.datasource.username: rapid_sit
spring.datasource.password: Hotfoot@123

#spring.datasource.url: jdbc:mysql://localhost:3306/bankstatement
#spring.datasource.username: root
#spring.datasource.password: root

spring.jpa.open-in-view: false

spring.jpa.properties.hibernate.dialect: org.hibernate.dialect.MySQL5InnoDBDialect
hibernate.dialect.storage_engine: innodb
spring.jpa.properties.hibernate.globally_quoted_identifiers: true 

spring.jpa.show-sql: true
spring.jpa.generate-ddl: true 
spring.main.allow-bean-definition-overriding: true

security.secretKey: 8b96bbf9
security.salt: 0x1b

report.downloadPath: 





perfios.returnUrl: https://usfb-rapid-sit.unitybank.co.in/
perfios.callBackUrl: https://usfb-rapid-sit.unitybank.co.in/forum-analysis/rest/external/perfios/save-transaction-detail?transaction_id=
perfios.vendor: centrum
perfios.host: demo.perfios.com
perfios.baseUrl: KuberaVault/insights
perfios.privateKeyPath: /home/vagrant/Downloads/private_key.txt
#perfios.private-key-path: /data/deployment/UNITY/common_platform/communication/perfios/private_key.txt
perfios.digestAlgorithm: SHA-1
perfios.signatureAlgorithm: RSA/ECB/PKCS1Padding
perfios.bsa.report.download.path: /data/deployment/UNITY/files/
perfios.version: 2.1
perfios.reportFormat: json
perfios.initTransactionUrl: /api/transaction/request
perfios.retrieveReportUrl: /retrieve 
perfios.txnStatusUrl: /txnstatus
