server:
  port: 9035
  servlet:
    context-path: /forum-analysis
    


spring.jpa.hibernate.ddl-auto: update
spring.datasource.url:  jdbc:mysql://localhost:3309/rapid_dev_forum?useUnicode=yes&characterEncoding=UTF-8
spring.datasource.username: rapid_sit
spring.datasource.password: Hotfoot@123

#spring.datasource.url: jdbc:mysql://localhost:3306/bankstatement
#spring.datasource.username: root
#spring.datasource.password: root

spring.jpa.open-in-view: false

spring.jpa.properties.hibernate.dialect: org.hibernate.dialect.MySQL5InnoDBDialect
hibernate.dialect.storage_engine: innodb
spring.jpa.properties.hibernate.globally_quoted_identifiers: true 

spring.jpa.show-sql: true
spring.jpa.generate-ddl: true 
spring.main.allow-bean-definition-overriding: true

security.secretKey: 8b96bbf9
security.salt: 0x1b

report.downloadPath: 

proofdocuments.upload_file_path: /home/vagrant/Downloads/perfios

perfios.bsa:
    upload:
      #private-key-path: /data/deployment/UNITY/common_platform/communication/perfios/perivate_key_upload.txt
      private-key-path: /home/vagrant/Downloads/perfios/perivate_key_upload.txt
      init.transaction.url: /KuberaVault/api/v3/organisations/centrum/transactions
      institution.list.url: /KuberaVault/api/v3/organisations/centrum/institutions
      encryption.algorithm: SHA256withRSA/PSS
      #file.url: /home/vagrant/Downloads/perfios
      file.url: /KuberaVault/api/v3/organisations/centrum/transactions/{perfiosTransactionId}/files
      file.path: /data/deployment/UNITY/files/
      file.process.url: /KuberaVault/api/v3/organisations/centrum/transactions/{perfiosTransactionId}/bank-statements
      retrieve.report.url: /KuberaVault/api/v3/organisations/centrum/transactions/{perfiosTransactionId}/reports
      generate.report.url: /KuberaVault/api/v3/organisations/centrum/transactions/{perfiosTransactionId}/reports
      transaction.status.url: /organisations/centrum/transactions/{perfiosTransactionId}/status
      callBackUrl: https://usfb-rapid-sit.unitybank.co.in/unity-external-integration/rest/perfios/bsa/external/callback



perfios.returnUrl: https://usfb-rapid-sit.unitybank.co.in/
perfios.callBackUrl: https://usfb-rapid-sit.unitybank.co.in/forum-analysis/rest/external/perfios/save-transaction-detail?transaction_id=
perfios.vendor: centrum
perfios.host: demo.perfios.com
perfios.baseUrl: KuberaVault/insights
perfios.privateKeyPath: /home/vagrant/Downloads/private_key.txt
#perfios.private-key-path: /data/deployment/UNITY/common_platform/communication/perfios/private_key.txt
perfios.digestAlgorithm: SHA-1
perfios.signatureAlgorithm: RSA/ECB/PKCS1Padding
perfios.bsa.report.download.path: /data/deployment/UNITY/files/
perfios.version: 2.1
perfios.reportFormat: json
perfios.initTransactionUrl: /api/transaction/request
perfios.retrieveReportUrl: /retrieve 
perfios.txnStatusUrl: /txnstatus
